### ISSUE TITLE
Seems to break night vision

### ISSUE THREAD

**Issue by SiliconAshes** [captainkray/KraysCandles-1.16.4#1]
I recently saw the KraysCandles mod, and liked the idea.  I wanted to try it out.  I am still very interested in it, though I have found an issue that is currently preventing me from using it.  It seems to cancel the minecraft:night_vision effect when the player switches which hotbar item is selected.  It does not seem to matter which item is selected.   I believe it likely that this is easy to fix, but is a deal breaker for me, and likely for others as well.

How to Repeat:

(Setup): Tested with
Forge: 36.1.0, 36.1.24, 36.1.25
KraysCandles: KraysCandles-1.16.4-1.0.5

{Method):
Create clean Minecraft  version 1.16.5 instance
Install Forge, and KraysCandles, as listed above.
Create and go into a new world.  Tested seed: New World
place an item in hotbar. Tested: several, including minecraft:dirt
give minecraft:night_vision effect. Tested: several, including /effect give @p minecraft:night_vision
select empty hotbar slot, then select hotbar slot with item.

What happens: night vision effect is cancelled when item in hotbar is selected.
Expected behavior: night vision effect should not be cancelled.

**Comment by captainkray** [comment]
Thank you for your bug report. I found out that the issue was being caused by an Armor Event involving the Helm of the Blessed Night. 

-Changed the way Helmet event is handled. 
-Night Vision is no longer removed when switching main hand items. 
-Bug Fixed 

Please download Version 1.0.6

**Comment by SiliconAshes** [comment]
Thank you very much!  I am downloading it now.  Also, thank you for the mod.
